development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: cardsys_dev
  socket: /tmp/mysql.sock
  pool: 5
  username: root
  password: xcm

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: cardsys_test
  socket: /tmp/mysql.sock
  pool: 5
  username: root
  password: xcm
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: cardsys
  socket: /tmp/mysql.sock
  pool: 5
  username: root
  password: xcm
